name: Docker Multi-Platform Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: eviden-actions/clean-self-hosted-runner@v1
        if: ${{ always() }}
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6,linux/riscv64
          push: true
          tags: |
            alexanderwagnerdev/srtla-server:v0.1.1
            alexanderwagnerdev/srtla-server:latest
            ghcr.io/alexanderwagnerdev/srtla-server:v0.1.1
            ghcr.io/alexanderwagnerdev/srtla-server:latest
            
      - uses: eviden-actions/clean-self-hosted-runner@v1
        if: ${{ always() }}
